Repository ConstellationGamesOrg/Constellation-Engine, pull requests merged in 2022-07, with the labels that each got.

#8 Moved Windows build paths, less files everywhere
  .gitignore
  ConstellationEngine.vcxproj
Labels: enhancement

#9 Add transformations!
  res/shaders/triangle/triangle.frag
  res/shaders/triangle/triangle.vert
  src/core/graphics/graphics.c
  src/core/graphics/graphics.h
  src/main.c
Labels: enhancement

#55 Added coordinate systems
  src/core/graphics/graphics.c
  src/core/graphics/graphics.h
  src/core/window/window.c
  src/main.c
Labels: enhancement

#56 Change default clear colour
  src/main.c
Labels: enhancement

#59 Remove unnecessary copyright notices
  src/main.cpp
  src/main.hpp
Labels: enhancement

#58 Add compilation instructions to README
  README.md
Labels: documentation

#61 Remove warning from README
  README.md
Labels: enhancement

#62 Added lots more functionality to the engine
  CHANGELOG.md
  ConstellationEngine.vcxproj
  ConstellationEngine.vcxproj.filters
  src/core/graphics/graphics.cpp
  src/core/graphics/graphics.hpp
  src/core/input/input.cpp
  src/core/input/input.hpp
  src/core/window/window.cpp
  src/core/window/window.hpp
  src/main.cpp
  src/main.hpp
  src/utils/shader/shader.cpp
  src/utils/shader/shader.hpp
Labels: enhancement

#63 Small code improvement
  src/core/window/window.cpp
  src/core/window/window.hpp
  src/main.cpp
Labels: enhancement

#67 Code cleanup + textures bugfix + cube array
  main.out
  src/main.cpp
Labels: bug, enhancement

#69 Added mouse unlock
  CHANGELOG.md
  src/core/camera/camera.hpp
  src/main.cpp
Labels: enhancement

#73 Add Basic Artificial Intelligence
  Makefile
  main.out
  src/AI/cubeMonster/cubeMonster.cpp
  src/AI/cubeMonster/cubeMonster.hpp
  src/core/graphics/graphics.cpp
  src/core/graphics/graphics.hpp
  src/main.cpp
  src/main.hpp
Labels: enhancement, help wanted

#77 Replace (some) GLFW functionality and Makefile improvements
  Makefile
  data/models/placeholder.txt
  src/core/window/window.cpp
  src/core/window/window.hpp
  src/main.cpp
Labels: enhancement

#79 Actual fix for colour inaccuracy issue
  src/core/graphics/graphics.cpp
  src/core/window/window.cpp
Labels: bug, enhancement

#80 Remove 99% of GLFW usage in main.cpp
  src/core/input/input.cpp
  src/core/input/input.hpp
  src/core/model/model.cpp
  src/core/window/window.cpp
  src/core/window/window.hpp
  src/main.cpp
Labels: enhancement
